//! `labcoat generate web` — deterministic TypeScript artifacts for browser
//! read clients.
//!
//! Inputs are the project's `labcoat.lock`, the built `build/*.abi.json`
//! artifacts, and the resolved network settings. Generation never touches
//! the network: the emitted client is *derived code* over verified local
//! state, exactly like the lockfile itself is a ledger of verified
//! deployments. The output is a self-contained module tree — no runtime
//! dependencies — that browsers use for reads only: indexed height, Alkanes
//! balances for an address, and ABI-typed `simulate` calls. No signing, no
//! key material, no state mutation.

use crate::abi::{self, AbiDocument};
use crate::error::{LabcoatError, Result};
use crate::lockfile::Lockfile;
use std::collections::BTreeMap;
use std::path::Path;

/// First line of every generated file; regeneration deletes exactly the
/// `.ts` files that start with this marker before writing fresh output.
pub const GENERATED_HEADER: &str = "// Generated by `labcoat generate web` — do not edit.";

/// One built contract artifact's ABI, as read from `build/`.
#[derive(Debug, Clone)]
pub struct BuildAbi {
    /// The artifact stem (Cargo package name), e.g. `overwrite-series`.
    pub artifact: String,
    pub abi: AbiDocument,
    /// sha256 of the sibling `<artifact>.wasm`, when present.
    pub wasm_sha256: Option<String>,
}

/// Everything web generation reads. No network access.
#[derive(Debug)]
pub struct WebInputs<'a> {
    /// Labcoat network target id (lockfile section), e.g. `labcoat`.
    pub network: &'a str,
    /// Bitcoin network parameters underneath the target, e.g. `regtest`.
    pub bitcoin_network: &'a str,
    /// The unified JSON-RPC endpoint (node + Alkanes secondary view).
    pub rpc_url: &'a str,
    pub lockfile: &'a Lockfile,
    pub abis: &'a [BuildAbi],
}

/// A generated file: path relative to the output directory, plus contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

/// Read every `build/*.abi.json` into a [`BuildAbi`], sorted by artifact
/// name. A missing build directory is an empty list (projects without
/// contracts still get a manifest and client); a malformed ABI file is an
/// error naming the file.
pub fn load_build_abis(build_dir: &Path) -> Result<Vec<BuildAbi>> {
    let entries = match std::fs::read_dir(build_dir) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => {
            return Err(LabcoatError::new(
                "CONFIG_INVALID",
                format!("cannot read {}: {e}", build_dir.display()),
                "pass --build-dir or run `labcoat build` first",
            ))
        }
    };
    let mut abis = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|e| {
            LabcoatError::new(
                "CONFIG_INVALID",
                format!("cannot read {}: {e}", build_dir.display()),
                "check permissions on the build directory",
            )
        })?;
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Some(artifact) = name.strip_suffix(".abi.json") else {
            continue;
        };
        let bytes = std::fs::read(&path).map_err(|e| {
            LabcoatError::new(
                "CONFIG_INVALID",
                format!("cannot read {}: {e}", path.display()),
                "re-run `labcoat build`",
            )
        })?;
        let abi = abi::parse(&bytes).map_err(|message| {
            LabcoatError::new(
                "CONFIG_INVALID",
                format!("{} is not a valid ABI: {message}", path.display()),
                "re-run `labcoat build` to regenerate the artifact",
            )
        })?;
        let wasm_sha256 = std::fs::read(build_dir.join(format!("{artifact}.wasm")))
            .ok()
            .map(|wasm| {
                use sha2::Digest;
                hex::encode(sha2::Sha256::digest(&wasm))
            });
        abis.push(BuildAbi {
            artifact: artifact.to_string(),
            abi,
            wasm_sha256,
        });
    }
    abis.sort_by(|a, b| a.artifact.cmp(&b.artifact));
    Ok(abis)
}

/// Generate the web artifact tree. Deterministic: identical inputs produce
/// byte-identical output (no timestamps, versions, or map ordering).
pub fn generate_web(inputs: &WebInputs<'_>) -> Result<Vec<GeneratedFile>> {
    let contracts = inputs
        .lockfile
        .networks
        .get(inputs.network)
        .cloned()
        .unwrap_or_default();

    let mut files = vec![
        GeneratedFile {
            path: "manifest.ts".to_string(),
            contents: manifest_ts(inputs, &contracts),
        },
        GeneratedFile {
            path: "abi/document.ts".to_string(),
            contents: abi_document_ts(),
        },
    ];
    for build_abi in inputs.abis {
        files.push(GeneratedFile {
            path: format!("abi/{}.ts", build_abi.artifact),
            contents: abi_contract_ts(build_abi),
        });
    }
    files.push(GeneratedFile {
        path: "abi/index.ts".to_string(),
        contents: abi_index_ts(inputs.abis),
    });
    files.push(GeneratedFile {
        path: "client.ts".to_string(),
        contents: client_ts(),
    });
    Ok(files)
}

/// Write the generated tree under `out_dir`, first deleting stale `.ts`
/// files that carry the generated header (and only those), so removed
/// contracts do not leave dead modules behind.
pub fn write_files(out_dir: &Path, files: &[GeneratedFile]) -> Result<()> {
    let io_err = |path: &Path, e: std::io::Error| {
        LabcoatError::new(
            "TOOLKIT_ERROR",
            format!("cannot write {}: {e}", path.display()),
            "check permissions on the output directory",
        )
    };
    remove_stale_generated(out_dir)?;
    for file in files {
        let path = out_dir.join(&file.path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| io_err(parent, e))?;
        }
        std::fs::write(&path, file.contents.as_bytes()).map_err(|e| io_err(&path, e))?;
    }
    Ok(())
}

fn remove_stale_generated(out_dir: &Path) -> Result<()> {
    for dir in [out_dir.to_path_buf(), out_dir.join("abi")] {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("ts") {
                continue;
            }
            let Ok(contents) = std::fs::read_to_string(&path) else {
                continue;
            };
            if contents.starts_with(GENERATED_HEADER) {
                std::fs::remove_file(&path).map_err(|e| {
                    LabcoatError::new(
                        "TOOLKIT_ERROR",
                        format!("cannot replace {}: {e}", path.display()),
                        "check permissions on the output directory",
                    )
                })?;
            }
        }
    }
    Ok(())
}

/// Escape a value into a double-quoted TypeScript string literal.
fn ts_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// A deterministic, always-valid TypeScript identifier for an artifact
/// name: `abi` + PascalCase over non-alphanumeric separators.
fn ts_identifier(artifact: &str) -> String {
    let mut out = String::from("abi");
    let mut upper_next = true;
    for c in artifact.chars() {
        if c.is_ascii_alphanumeric() {
            if upper_next {
                out.extend(c.to_uppercase());
            } else {
                out.push(c);
            }
            upper_next = false;
        } else {
            upper_next = true;
        }
    }
    out
}

/// The single chain id shared by every record, when they agree.
fn common_chain_id(contracts: &BTreeMap<String, crate::lockfile::Deployment>) -> Option<String> {
    let mut common: Option<&str> = None;
    for deployment in contracts.values() {
        match (&deployment.chain_id, common) {
            (None, _) => return None,
            (Some(id), None) => common = Some(id),
            (Some(id), Some(seen)) if id != seen => return None,
            _ => {}
        }
    }
    common.map(String::from)
}

/// Link a deployment to the local build artifact whose ABI describes it:
/// exact wasm-hash match first, then an artifact of the same name.
fn artifact_for<'a>(
    name: &str,
    deployment: &crate::lockfile::Deployment,
    abis: &'a [BuildAbi],
) -> Option<&'a str> {
    if let Some(hash) = &deployment.wasm_sha256 {
        if let Some(build_abi) = abis.iter().find(|a| {
            a.wasm_sha256
                .as_deref()
                .is_some_and(|h| h.eq_ignore_ascii_case(hash))
        }) {
            return Some(&build_abi.artifact);
        }
    }
    abis.iter()
        .find(|a| a.artifact == name)
        .map(|a| a.artifact.as_str())
}

fn optional_ts_string(value: Option<&str>) -> String {
    match value {
        Some(value) => ts_string(value),
        None => "null".to_string(),
    }
}

fn manifest_ts(
    inputs: &WebInputs<'_>,
    contracts: &BTreeMap<String, crate::lockfile::Deployment>,
) -> String {
    let mut entries = String::new();
    for (name, deployment) in contracts {
        let artifact = artifact_for(name, deployment, inputs.abis);
        entries.push_str(&format!(
            "    {}: {{\n      id: {},\n      txid: {},\n      wasmSha256: {},\n      chainId: {},\n      artifact: {},\n    }},\n",
            ts_string(name),
            ts_string(&deployment.alkanes_id),
            ts_string(&deployment.txid),
            optional_ts_string(deployment.wasm_sha256.as_deref()),
            optional_ts_string(deployment.chain_id.as_deref()),
            optional_ts_string(artifact),
        ));
    }
    format!(
        r#"{header}
//
// Derived from labcoat.lock (network {network_comment}) and built ABI
// artifacts. Regenerate after every deploy or ABI change.

/** One labcoat.lock deployment record, projected for browser reads. */
export interface ContractDeployment {{
  /** Alkanes id as canonical decimal "block:tx". */
  id: string
  /** Deploy transaction id. */
  txid: string
  /** sha256 of the deployed wasm, when recorded. */
  wasmSha256: string | null
  /** Chain instance id (the hash of block 1) the record was written against. */
  chainId: string | null
  /** Local build artifact whose ABI describes this deployment, when known. */
  artifact: string | null
}}

export interface WebManifest {{
  /** Labcoat network target these artifacts were generated for. */
  network: string
  /** Bitcoin network parameters underneath the target. */
  bitcoinNetwork: string
  /**
   * The unified JSON-RPC endpoint (node + Alkanes secondary view) at
   * generation time. Browsers normally reach it through a same-origin dev
   * proxy or rewrite instead of calling it directly.
   */
  rpcUrl: string
  /**
   * Chain instance id shared by every deployment record, or null when
   * records are missing one or disagree. Compare against live chain state
   * to detect a reset network with stale records.
   */
  chainId: string | null
  /** Deployment records keyed by labcoat.lock contract name. */
  contracts: Record<string, ContractDeployment>
}}

export const MANIFEST: WebManifest = {{
  network: {network},
  bitcoinNetwork: {bitcoin_network},
  rpcUrl: {rpc_url},
  chainId: {chain_id},
  contracts: {{
{entries}  }},
}}
"#,
        header = GENERATED_HEADER,
        network_comment = ts_string(inputs.network),
        network = ts_string(inputs.network),
        bitcoin_network = ts_string(inputs.bitcoin_network),
        rpc_url = ts_string(inputs.rpc_url),
        chain_id = optional_ts_string(common_chain_id(contracts).as_deref()),
        entries = entries,
    )
}

fn abi_document_ts() -> String {
    format!(
        r#"{GENERATED_HEADER}

/** One typed parameter of an ABI method. */
export interface AbiParam {{
  name: string
  /** ABI type name, e.g. "u128", "AlkaneId", "String". */
  type: string
}}

/** One contract method: dispatch opcode plus its typed signature. */
export interface AbiMethod {{
  name: string
  /** Dispatch opcode (a u128). */
  opcode: bigint
  params: AbiParam[]
  /** ABI return type name, e.g. "u128", "String", "Vec<u8>", "void". */
  returns: string
}}

/** A contract ABI as extracted from its canonical `__meta` export. */
export interface AbiDocument {{
  contract: string
  methods: AbiMethod[]
}}
"#,
    )
}

fn abi_contract_ts(build_abi: &BuildAbi) -> String {
    let mut methods = String::new();
    for method in &build_abi.abi.methods {
        let mut params = String::new();
        for param in &method.params {
            params.push_str(&format!(
                "\n        {{ name: {}, type: {} }},",
                ts_string(&param.name),
                ts_string(&param.type_),
            ));
        }
        let params = if params.is_empty() {
            "[]".to_string()
        } else {
            format!("[{params}\n      ]")
        };
        methods.push_str(&format!(
            "    {{\n      name: {},\n      opcode: {}n,\n      params: {},\n      returns: {},\n    }},\n",
            ts_string(&method.name),
            method.opcode,
            params,
            ts_string(&method.returns),
        ));
    }
    format!(
        r#"{header}

import type {{ AbiDocument }} from "./document"

/** ABI of the {artifact} build artifact. */
export const {identifier}: AbiDocument = {{
  contract: {contract},
  methods: [
{methods}  ],
}}
"#,
        header = GENERATED_HEADER,
        artifact = build_abi.artifact,
        identifier = ts_identifier(&build_abi.artifact),
        contract = ts_string(&build_abi.abi.contract),
        methods = methods,
    )
}

fn abi_index_ts(abis: &[BuildAbi]) -> String {
    let mut imports = String::new();
    let mut entries = String::new();
    for build_abi in abis {
        imports.push_str(&format!(
            "import {{ {} }} from \"./{}\"\n",
            ts_identifier(&build_abi.artifact),
            build_abi.artifact,
        ));
        entries.push_str(&format!(
            "  {}: {},\n",
            ts_string(&build_abi.artifact),
            ts_identifier(&build_abi.artifact),
        ));
    }
    format!(
        r#"{GENERATED_HEADER}

import type {{ AbiDocument }} from "./document"
{imports}
export type {{ AbiDocument, AbiMethod, AbiParam }} from "./document"

/** Every built contract ABI, keyed by build artifact name. */
export const ABIS: Record<string, AbiDocument> = {{
{entries}}}
"#,
    )
}

fn client_ts() -> String {
    format!("{GENERATED_HEADER}\n{CLIENT_TS_BODY}")
}

/// The static read client. Wire protocol notes:
///
/// - The unified endpoint is Qubitcoin JSON-RPC 2.0. The Alkanes indexer is
///   exposed as a secondary view: `secondaryheight ["alkanes"]` returns the
///   indexed height, and `secondaryview ["alkanes", <view>, "0x<hex>"]`
///   evaluates a metashrew view function over protobuf-encoded parameters,
///   returning protobuf bytes as a hex string.
/// - `simulate` takes an `alkanes.MessageContextParcel` whose calldata is
///   the LEB128 varint list `[block, tx, opcode, ...args]` (a cellpack) and
///   returns an `alkanes.SimulateResponse`.
/// - `protorunesbyaddress` takes a `protorune.ProtorunesWalletRequest`
///   (wallet = address bytes, protocol_tag = 1 for Alkanes) and returns a
///   `protorune.WalletResponse` whose outpoint balance sheets are summed
///   per Alkane here, mirroring the CLI's `labcoat balance`.
const CLIENT_TS_BODY: &str = r#"//
// Read-only browser client for the Labcoat unified JSON-RPC endpoint
// (Qubitcoin node + Alkanes secondary view). No signing, no key material,
// no state mutation. Self-contained: no runtime dependencies.

import { MANIFEST } from "./manifest"
import { ABIS } from "./abi"
import type { AbiMethod } from "./abi"

const U128_MAX = (1n << 128n) - 1n
const ALKANES_PROTOCOL_TAG = 1n

/* ---------------------------------- hex ---------------------------------- */

function bytesToHex(bytes: Uint8Array): string {
  let out = ""
  for (const byte of bytes) out += byte.toString(16).padStart(2, "0")
  return out
}

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex
  if (clean.length % 2 !== 0 || /[^0-9a-fA-F]/.test(clean)) {
    throw new LabcoatClientError("RESPONSE_INVALID", `invalid hex payload: ${hex.slice(0, 32)}…`)
  }
  const bytes = new Uint8Array(clean.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

/* --------------------------- LEB128 / protobuf ---------------------------- */

function pushVarint(out: number[], value: bigint): void {
  if (value < 0n) throw new LabcoatClientError("ARG_INVALID", "varint values must be non-negative")
  let v = value
  for (;;) {
    const byte = Number(v & 0x7fn)
    v >>= 7n
    if (v === 0n) {
      out.push(byte)
      return
    }
    out.push(byte | 0x80)
  }
}

/** LEB128 varint list — the cellpack encoding: [block, tx, opcode, ...args]. */
function encodeCellpack(values: bigint[]): Uint8Array {
  const out: number[] = []
  for (const value of values) pushVarint(out, value)
  return Uint8Array.from(out)
}

function pushProtoVarintField(out: number[], field: number, value: bigint): void {
  pushVarint(out, BigInt(field * 8))
  pushVarint(out, value)
}

function pushProtoBytesField(out: number[], field: number, value: Uint8Array): void {
  pushVarint(out, BigInt(field * 8 + 2))
  pushVarint(out, BigInt(value.length))
  for (const byte of value) out.push(byte)
}

/** Minimal protobuf wire reader (varint + length-delimited + fixed skips). */
class ProtoReader {
  private offset = 0

  constructor(private readonly bytes: Uint8Array) {}

  atEnd(): boolean {
    return this.offset >= this.bytes.length
  }

  readVarint(): bigint {
    let value = 0n
    let shift = 0n
    for (;;) {
      if (this.offset >= this.bytes.length) {
        throw new LabcoatClientError("RESPONSE_INVALID", "truncated protobuf varint")
      }
      const byte = this.bytes[this.offset++]
      value |= BigInt(byte & 0x7f) << shift
      if ((byte & 0x80) === 0) return value
      shift += 7n
      if (shift > 133n) {
        throw new LabcoatClientError("RESPONSE_INVALID", "oversized protobuf varint")
      }
    }
  }

  readField(): { field: number; wire: number } {
    const tag = this.readVarint()
    return { field: Number(tag >> 3n), wire: Number(tag & 7n) }
  }

  readBytes(): Uint8Array {
    const length = Number(this.readVarint())
    if (this.offset + length > this.bytes.length) {
      throw new LabcoatClientError("RESPONSE_INVALID", "truncated protobuf payload")
    }
    const slice = this.bytes.subarray(this.offset, this.offset + length)
    this.offset += length
    return slice
  }

  skip(wire: number): void {
    if (wire === 0) {
      this.readVarint()
    } else if (wire === 1) {
      this.offset += 8
    } else if (wire === 2) {
      this.readBytes()
    } else if (wire === 5) {
      this.offset += 4
    } else {
      throw new LabcoatClientError("RESPONSE_INVALID", `unsupported protobuf wire type ${wire}`)
    }
    if (this.offset > this.bytes.length) {
      throw new LabcoatClientError("RESPONSE_INVALID", "truncated protobuf payload")
    }
  }
}

/** protorune/alkanes uint128 message: { lo: u64 = 1, hi: u64 = 2 }. */
function decodeUint128(bytes: Uint8Array): bigint {
  const reader = new ProtoReader(bytes)
  let lo = 0n
  let hi = 0n
  while (!reader.atEnd()) {
    const { field, wire } = reader.readField()
    if (field === 1 && wire === 0) lo = reader.readVarint()
    else if (field === 2 && wire === 0) hi = reader.readVarint()
    else reader.skip(wire)
  }
  return (hi << 64n) | lo
}

/* --------------------------------- errors --------------------------------- */

export type LabcoatClientErrorCode =
  | "RPC_UNREACHABLE"
  | "RPC_ERROR"
  | "RESPONSE_INVALID"
  | "CONTRACT_UNKNOWN"
  | "METHOD_UNKNOWN"
  | "ARG_INVALID"

export class LabcoatClientError extends Error {
  constructor(
    public readonly code: LabcoatClientErrorCode,
    message: string,
  ) {
    super(message)
    this.name = "LabcoatClientError"
  }
}

/* --------------------------------- results -------------------------------- */

export interface AlkaneRef {
  /** Canonical decimal digits. */
  block: string
  tx: string
}

export interface AlkaneBalance {
  id: AlkaneRef
  /** "block:tx" convenience key. */
  key: string
  name: string
  symbol: string
  /** Total base units across every outpoint the address controls. */
  balance: bigint
}

export type SimulateValue = bigint | string | Uint8Array | AlkaneRef | null

export interface SimulateResult {
  status: "success" | "revert"
  gasUsed: bigint
  /** Revert reason, when the contract reverted. */
  error: string | null
  /** Raw return bytes. */
  data: Uint8Array
  /**
   * `data` decoded per the ABI return type: u128 → bigint, String → string,
   * AlkaneId → { block, tx } decimal strings, Vec<u8> → Uint8Array. Null on
   * revert, `void` returns, numeric-opcode calls, and unknown types.
   */
  value: SimulateValue
}

/** One argument per ABI parameter: bigint/number, decimal or 0x-hex string,
 * "block:tx" for AlkaneId parameters, or arbitrary text for String ones. */
export type SimulateArg = bigint | number | string

/* ------------------------------ arg encoding ------------------------------ */

function parseU128(value: SimulateArg, label: string): bigint {
  let parsed: bigint
  if (typeof value === "bigint") {
    parsed = value
  } else if (typeof value === "number") {
    if (!Number.isSafeInteger(value) || value < 0) {
      throw new LabcoatClientError("ARG_INVALID", `${label} must be a non-negative safe integer`)
    }
    parsed = BigInt(value)
  } else if (/^0x[0-9a-fA-F]+$/.test(value)) {
    parsed = BigInt(value)
  } else if (/^(0|[1-9][0-9]*)$/.test(value)) {
    parsed = BigInt(value)
  } else {
    throw new LabcoatClientError("ARG_INVALID", `${label} must be a canonical decimal or 0x-hex u128`)
  }
  if (parsed < 0n || parsed > U128_MAX) {
    throw new LabcoatClientError("ARG_INVALID", `${label} does not fit in a u128`)
  }
  return parsed
}

function parseAlkaneRef(value: SimulateArg, label: string): { block: bigint; tx: bigint } {
  if (typeof value !== "string" || !value.includes(":")) {
    throw new LabcoatClientError("ARG_INVALID", `${label} must use decimal "block:tx" syntax`)
  }
  const [block, tx, ...rest] = value.split(":")
  if (rest.length > 0) {
    throw new LabcoatClientError("ARG_INVALID", `${label} must use decimal "block:tx" syntax`)
  }
  return {
    block: parseU128(block, `${label} block`),
    tx: parseU128(tx, `${label} tx`),
  }
}

/** NUL-terminated UTF-8 packed into little-endian u128 cellpack words. */
function encodeStringArg(value: SimulateArg, label: string): bigint[] {
  if (typeof value !== "string") {
    throw new LabcoatClientError("ARG_INVALID", `${label} must be a string`)
  }
  const bytes = new TextEncoder().encode(value)
  if (bytes.includes(0)) {
    throw new LabcoatClientError("ARG_INVALID", `${label} cannot contain a null byte`)
  }
  const terminated = new Uint8Array(bytes.length + 1)
  terminated.set(bytes)
  const words: bigint[] = []
  for (let i = 0; i < terminated.length; i += 16) {
    const chunk = terminated.subarray(i, i + 16)
    let word = 0n
    for (let j = 0; j < chunk.length; j++) {
      word |= BigInt(chunk[j]) << BigInt(8 * j)
    }
    words.push(word)
  }
  return words
}

function encodeAbiArgs(method: AbiMethod, args: SimulateArg[]): bigint[] {
  if (args.length !== method.params.length) {
    const expected = method.params.map((p) => `${p.name}: ${p.type}`).join(", ")
    throw new LabcoatClientError(
      "ARG_INVALID",
      `method ${method.name} expects ${method.params.length} parameter(s) (${expected}), received ${args.length}`,
    )
  }
  const words: bigint[] = []
  for (let i = 0; i < method.params.length; i++) {
    const param = method.params[i]
    const label = `parameter ${param.name}`
    if (param.type === "u128") {
      words.push(parseU128(args[i], label))
    } else if (param.type === "AlkaneId") {
      const ref = parseAlkaneRef(args[i], label)
      words.push(ref.block, ref.tx)
    } else if (param.type === "String") {
      words.push(...encodeStringArg(args[i], label))
    } else {
      throw new LabcoatClientError(
        "ARG_INVALID",
        `ABI type ${param.type} is not supported by the generated client`,
      )
    }
  }
  return words
}

/* ----------------------------- return decoding ---------------------------- */

function decodeLeU128(bytes: Uint8Array): bigint {
  let value = 0n
  for (let i = 0; i < bytes.length; i++) {
    value |= BigInt(bytes[i]) << BigInt(8 * i)
  }
  return value
}

function decodeReturn(returns: string, data: Uint8Array): SimulateValue {
  if (returns === "u128") {
    if (data.length > 16) return null
    return decodeLeU128(data)
  }
  if (returns === "String") {
    return new TextDecoder("utf-8", { fatal: false }).decode(data)
  }
  if (returns === "Vec<u8>") {
    return data
  }
  if (returns === "AlkaneId") {
    if (data.length !== 32) return null
    return {
      block: decodeLeU128(data.subarray(0, 16)).toString(),
      tx: decodeLeU128(data.subarray(16, 32)).toString(),
    }
  }
  return null
}

/* ------------------------------- the client ------------------------------- */

export interface LabcoatWebClientOptions {
  /**
   * JSON-RPC endpoint the browser can actually reach — typically a
   * same-origin path (e.g. "/rpc") proxied to the manifest's rpcUrl by the
   * app's dev server. Defaults to the manifest's rpcUrl.
   */
  baseUrl?: string
  /** Fetch implementation (for tests and non-browser runtimes). */
  fetchFn?: typeof fetch
}

export class LabcoatWebClient {
  readonly baseUrl: string
  private readonly fetchFn: typeof fetch
  private requestId = 0

  constructor(options: LabcoatWebClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? MANIFEST.rpcUrl
    const fetchFn = options.fetchFn ?? globalThis.fetch
    if (typeof fetchFn !== "function") {
      throw new LabcoatClientError("RPC_UNREACHABLE", "no fetch implementation available")
    }
    this.fetchFn = fetchFn.bind(globalThis)
  }

  private async rpc(method: string, params: unknown[]): Promise<unknown> {
    let response: Response
    try {
      response = await this.fetchFn(this.baseUrl, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ jsonrpc: "2.0", id: ++this.requestId, method, params }),
      })
    } catch (cause) {
      throw new LabcoatClientError(
        "RPC_UNREACHABLE",
        `cannot reach ${this.baseUrl}: ${cause instanceof Error ? cause.message : String(cause)}`,
      )
    }
    if (!response.ok) {
      throw new LabcoatClientError("RPC_ERROR", `${method} failed: HTTP ${response.status}`)
    }
    let envelope: { result?: unknown; error?: { message?: string; code?: number } | null }
    try {
      envelope = (await response.json()) as typeof envelope
    } catch {
      throw new LabcoatClientError("RESPONSE_INVALID", `${method} returned a non-JSON body`)
    }
    if (envelope.error != null) {
      throw new LabcoatClientError(
        "RPC_ERROR",
        `${method} failed: ${envelope.error.message ?? JSON.stringify(envelope.error)}`,
      )
    }
    return envelope.result
  }

  /** A metashrew view over the Alkanes secondary index; protobuf in and out. */
  private async view(view: string, request: Uint8Array): Promise<Uint8Array> {
    const result = await this.rpc("secondaryview", [
      "alkanes",
      view,
      `0x${bytesToHex(request)}`,
    ])
    if (typeof result !== "string") {
      throw new LabcoatClientError("RESPONSE_INVALID", `${view} returned a non-string result`)
    }
    return hexToBytes(result)
  }

  /** Height of the Alkanes secondary index — the state every read reflects. */
  async getIndexedHeight(): Promise<number> {
    const result = await this.rpc("secondaryheight", ["alkanes"])
    const height =
      typeof result === "number"
        ? result
        : typeof result === "string"
          ? Number.parseInt(result, 10)
          : Number.NaN
    if (!Number.isSafeInteger(height) || height < 0) {
      throw new LabcoatClientError("RESPONSE_INVALID", `invalid indexed height: ${String(result)}`)
    }
    return height
  }

  /**
   * Alkanes balances held by `address`, summed across its outpoints and
   * sorted by Alkane id. Amounts are full u128 base units.
   */
  async getAlkanesBalances(address: string): Promise<AlkaneBalance[]> {
    if (address.length === 0) {
      throw new LabcoatClientError("ARG_INVALID", "address must not be empty")
    }
    // protorune.ProtorunesWalletRequest { wallet = 1, protocol_tag = 2 }
    const request: number[] = []
    pushProtoBytesField(request, 1, new TextEncoder().encode(address))
    const protocolTag: number[] = []
    pushProtoVarintField(protocolTag, 1, ALKANES_PROTOCOL_TAG)
    pushProtoBytesField(request, 2, Uint8Array.from(protocolTag))

    const response = await this.view("protorunesbyaddress", Uint8Array.from(request))
    const totals = new Map<string, { block: bigint; tx: bigint; name: string; symbol: string; balance: bigint }>()

    // protorune.WalletResponse { outpoints: OutpointResponse[] = 1 }
    const wallet = new ProtoReader(response)
    while (!wallet.atEnd()) {
      const { field, wire } = wallet.readField()
      if (field !== 1 || wire !== 2) {
        wallet.skip(wire)
        continue
      }
      // OutpointResponse { balances: BalanceSheet = 1 }
      const outpoint = new ProtoReader(wallet.readBytes())
      while (!outpoint.atEnd()) {
        const item = outpoint.readField()
        if (item.field !== 1 || item.wire !== 2) {
          outpoint.skip(item.wire)
          continue
        }
        // BalanceSheet { entries: BalanceSheetItem[] = 1 }
        const sheet = new ProtoReader(outpoint.readBytes())
        while (!sheet.atEnd()) {
          const entry = sheet.readField()
          if (entry.field !== 1 || entry.wire !== 2) {
            sheet.skip(entry.wire)
            continue
          }
          decodeBalanceSheetItem(sheet.readBytes(), totals)
        }
      }
    }

    const balances = [...totals.values()].map((entry) => ({
      id: { block: entry.block.toString(), tx: entry.tx.toString() },
      key: `${entry.block}:${entry.tx}`,
      name: entry.name,
      symbol: entry.symbol,
      balance: entry.balance,
    }))
    balances.sort((left, right) => {
      const leftBlock = BigInt(left.id.block)
      const rightBlock = BigInt(right.id.block)
      if (leftBlock !== rightBlock) return leftBlock < rightBlock ? -1 : 1
      const leftTx = BigInt(left.id.tx)
      const rightTx = BigInt(right.id.tx)
      if (leftTx === rightTx) return 0
      return leftTx < rightTx ? -1 : 1
    })
    return balances
  }

  /**
   * Read-only simulation against indexed chain state. `contract` is a
   * manifest contract name or a "block:tx" id; `method` is an ABI method
   * name (typed args, decoded return) or a decimal opcode (raw u128 args,
   * raw return). Pass `options.height` to reuse an already-fetched indexed
   * height and save a round trip.
   */
  async simulate(
    contract: string,
    method: string,
    args: SimulateArg[] = [],
    options: { height?: number } = {},
  ): Promise<SimulateResult> {
    const target = this.resolveContract(contract)
    let opcode: bigint
    let words: bigint[]
    let returns: string | null
    if (/^(0|[1-9][0-9]*)$/.test(method)) {
      opcode = parseU128(method, "opcode")
      words = args.map((arg, index) => parseU128(arg, `argument ${index}`))
      returns = null
    } else {
      const abiMethod = this.resolveMethod(target, method)
      opcode = abiMethod.opcode
      words = encodeAbiArgs(abiMethod, args)
      returns = abiMethod.returns
    }

    const height = options.height ?? (await this.getIndexedHeight())
    const calldata = encodeCellpack([target.block, target.tx, opcode, ...words])
    // alkanes.MessageContextParcel { height = 4, calldata = 5 }
    const parcel: number[] = []
    pushProtoVarintField(parcel, 4, BigInt(height))
    pushProtoBytesField(parcel, 5, calldata)

    const response = await this.view("simulate", Uint8Array.from(parcel))

    // alkanes.SimulateResponse { execution = 1, gas_used = 2, error = 3 }
    let data: Uint8Array = new Uint8Array(0)
    let gasUsed = 0n
    let error: string | null = null
    const reader = new ProtoReader(response)
    while (!reader.atEnd()) {
      const { field, wire } = reader.readField()
      if (field === 1 && wire === 2) {
        // alkanes.ExtendedCallResponse { data = 3 }
        const execution = new ProtoReader(reader.readBytes())
        while (!execution.atEnd()) {
          const item = execution.readField()
          if (item.field === 3 && item.wire === 2) data = execution.readBytes()
          else execution.skip(item.wire)
        }
      } else if (field === 2 && wire === 0) {
        gasUsed = reader.readVarint()
      } else if (field === 3 && wire === 2) {
        error = new TextDecoder("utf-8", { fatal: false }).decode(reader.readBytes())
        if (error.length === 0) error = null
      } else {
        reader.skip(wire)
      }
    }

    const status = error === null ? "success" : "revert"
    return {
      status,
      gasUsed,
      error,
      data,
      value: status === "success" && returns !== null ? decodeReturn(returns, data) : null,
    }
  }

  private resolveContract(contract: string): { block: bigint; tx: bigint; artifact: string | null } {
    if (contract.includes(":")) {
      const ref = parseAlkaneRef(contract, "contract id")
      return { block: ref.block, tx: ref.tx, artifact: null }
    }
    const deployment = MANIFEST.contracts[contract]
    if (deployment === undefined) {
      const known = Object.keys(MANIFEST.contracts).join(", ")
      throw new LabcoatClientError(
        "CONTRACT_UNKNOWN",
        `no contract "${contract}" in the generated manifest${known.length > 0 ? ` (known: ${known})` : ""}`,
      )
    }
    const ref = parseAlkaneRef(deployment.id, `manifest id for ${contract}`)
    return { block: ref.block, tx: ref.tx, artifact: deployment.artifact }
  }

  private resolveMethod(
    target: { artifact: string | null },
    method: string,
  ): AbiMethod {
    if (target.artifact === null) {
      throw new LabcoatClientError(
        "METHOD_UNKNOWN",
        `method "${method}" needs ABI metadata; call by manifest contract name or use a numeric opcode`,
      )
    }
    const abi = ABIS[target.artifact]
    const resolved = abi?.methods.find((candidate) => candidate.name === method)
    if (resolved === undefined) {
      const available = abi?.methods.map((candidate) => candidate.name).join(", ") ?? ""
      throw new LabcoatClientError(
        "METHOD_UNKNOWN",
        `ABI method "${method}" was not found${available.length > 0 ? `; available methods: ${available}` : ""}`,
      )
    }
    return resolved
  }
}

function decodeBalanceSheetItem(
  bytes: Uint8Array,
  totals: Map<string, { block: bigint; tx: bigint; name: string; symbol: string; balance: bigint }>,
): void {
  // protorune.BalanceSheetItem { rune: Rune = 1, balance: uint128 = 2 }
  let block: bigint | null = null
  let tx: bigint | null = null
  let name = ""
  let symbol = ""
  let balance = 0n
  const reader = new ProtoReader(bytes)
  while (!reader.atEnd()) {
    const { field, wire } = reader.readField()
    if (field === 1 && wire === 2) {
      // protorune.Rune { runeId = 1, name = 2, symbol = 5 }
      const rune = new ProtoReader(reader.readBytes())
      while (!rune.atEnd()) {
        const item = rune.readField()
        if (item.field === 1 && item.wire === 2) {
          // protorune.ProtoruneRuneId { height: uint128 = 1, txindex: uint128 = 2 }
          const runeId = new ProtoReader(rune.readBytes())
          while (!runeId.atEnd()) {
            const part = runeId.readField()
            if (part.field === 1 && part.wire === 2) block = decodeUint128(runeId.readBytes())
            else if (part.field === 2 && part.wire === 2) tx = decodeUint128(runeId.readBytes())
            else runeId.skip(part.wire)
          }
        } else if (item.field === 2 && item.wire === 2) {
          name = new TextDecoder("utf-8", { fatal: false }).decode(rune.readBytes())
        } else if (item.field === 5 && item.wire === 2) {
          symbol = new TextDecoder("utf-8", { fatal: false }).decode(rune.readBytes())
        } else {
          rune.skip(item.wire)
        }
      }
    } else if (field === 2 && wire === 2) {
      balance = decodeUint128(reader.readBytes())
    } else {
      reader.skip(wire)
    }
  }
  if (block === null || tx === null) return
  const key = `${block}:${tx}`
  const existing = totals.get(key)
  if (existing === undefined) {
    totals.set(key, { block, tx, name, symbol, balance })
  } else {
    existing.balance += balance
    if (existing.name.length === 0) existing.name = name
    if (existing.symbol.length === 0) existing.symbol = symbol
  }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lockfile::Deployment;

    fn deployment(id: &str, wasm: Option<&str>, chain: Option<&str>) -> Deployment {
        Deployment {
            alkanes_id: id.to_string(),
            wasm_sha256: wasm.map(String::from),
            txid: "ab".repeat(32),
            block: None,
            status: "success".to_string(),
            deployed_at: 0,
            chain_id: chain.map(String::from),
        }
    }

    fn build_abi(artifact: &str, wasm_sha256: Option<&str>) -> BuildAbi {
        BuildAbi {
            artifact: artifact.to_string(),
            abi: abi::parse(
                br#"{"contract":"Token","methods":[{"name":"get_value","opcode":101,"params":[],"returns":"u128"}]}"#,
            )
            .unwrap(),
            wasm_sha256: wasm_sha256.map(String::from),
        }
    }

    #[test]
    fn escapes_typescript_strings() {
        assert_eq!(ts_string("plain"), "\"plain\"");
        assert_eq!(ts_string("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(ts_string("line\nbreak\ttab"), "\"line\\nbreak\\ttab\"");
        assert_eq!(ts_string("bell\u{7}"), "\"bell\\u0007\"");
    }

    #[test]
    fn artifact_identifiers_are_valid_and_deterministic() {
        assert_eq!(ts_identifier("overwrite-series"), "abiOverwriteSeries");
        assert_eq!(ts_identifier("counter"), "abiCounter");
        assert_eq!(ts_identifier("2fast_2furious"), "abi2fast2furious");
    }

    #[test]
    fn chain_id_folds_only_when_all_records_agree() {
        let mut contracts = BTreeMap::new();
        contracts.insert("a".to_string(), deployment("2:1", None, Some("x")));
        contracts.insert("b".to_string(), deployment("2:2", None, Some("x")));
        assert_eq!(common_chain_id(&contracts).as_deref(), Some("x"));

        contracts.insert("c".to_string(), deployment("2:3", None, Some("y")));
        assert_eq!(common_chain_id(&contracts), None);

        let mut missing = BTreeMap::new();
        missing.insert("a".to_string(), deployment("2:1", None, None));
        assert_eq!(common_chain_id(&missing), None);
        assert_eq!(common_chain_id(&BTreeMap::new()), None);
    }

    #[test]
    fn artifacts_link_by_wasm_hash_then_name() {
        let abis = vec![
            build_abi("token", Some("aa")),
            build_abi("series", Some("bb")),
        ];

        // Hash match wins even when the deployment name differs.
        let renamed = deployment("4:1", Some("BB"), None);
        assert_eq!(artifact_for("usd", &renamed, &abis), Some("series"));

        // No hash falls back to a same-name artifact.
        let named = deployment("4:2", None, None);
        assert_eq!(artifact_for("token", &named, &abis), Some("token"));

        // Neither matches: no ABI link.
        let unknown = deployment("4:3", Some("cc"), None);
        assert_eq!(artifact_for("mystery", &unknown, &abis), None);
    }

    #[test]
    fn generation_is_deterministic_and_headed() {
        let mut networks = BTreeMap::new();
        let mut contracts = BTreeMap::new();
        contracts.insert(
            "token".to_string(),
            deployment("4:1", Some("aa"), Some("x")),
        );
        networks.insert("labcoat".to_string(), contracts);
        let lockfile = Lockfile {
            version: 1,
            networks,
        };
        let abis = vec![build_abi("token", Some("aa"))];
        let inputs = WebInputs {
            network: "labcoat",
            bitcoin_network: "regtest",
            rpc_url: "http://127.0.0.1:18443",
            lockfile: &lockfile,
            abis: &abis,
        };

        let first = generate_web(&inputs).unwrap();
        let second = generate_web(&inputs).unwrap();
        assert_eq!(first, second);

        let paths: Vec<&str> = first.iter().map(|f| f.path.as_str()).collect();
        assert_eq!(
            paths,
            vec![
                "manifest.ts",
                "abi/document.ts",
                "abi/token.ts",
                "abi/index.ts",
                "client.ts"
            ]
        );
        for file in &first {
            assert!(
                file.contents.starts_with(GENERATED_HEADER),
                "{} is missing the generated header",
                file.path
            );
        }
        let manifest = &first[0].contents;
        assert!(manifest.contains("id: \"4:1\""));
        assert!(manifest.contains("artifact: \"token\""));
        assert!(manifest.contains("chainId: \"x\""));
    }

    #[test]
    fn missing_network_section_generates_an_empty_manifest() {
        let lockfile = Lockfile {
            version: 1,
            networks: BTreeMap::new(),
        };
        let inputs = WebInputs {
            network: "labcoat",
            bitcoin_network: "regtest",
            rpc_url: "http://127.0.0.1:18443",
            lockfile: &lockfile,
            abis: &[],
        };
        let files = generate_web(&inputs).unwrap();
        let manifest = &files[0].contents;
        assert!(manifest.contains("contracts: {\n  },"));
        assert!(manifest.contains("chainId: null"));
    }

    #[test]
    fn stale_generated_files_are_replaced_and_foreign_files_kept() {
        let root = std::env::temp_dir().join(format!("labcoat-generate-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("abi")).unwrap();
        std::fs::write(
            root.join("abi/removed-contract.ts"),
            format!("{GENERATED_HEADER}\nexport const gone = 1\n"),
        )
        .unwrap();
        std::fs::write(root.join("hand-written.ts"), "export const keep = 1\n").unwrap();

        let files = vec![GeneratedFile {
            path: "manifest.ts".to_string(),
            contents: format!("{GENERATED_HEADER}\nexport const MANIFEST = {{}}\n"),
        }];
        write_files(&root, &files).unwrap();

        assert!(root.join("manifest.ts").exists());
        assert!(root.join("hand-written.ts").exists());
        assert!(!root.join("abi/removed-contract.ts").exists());
        std::fs::remove_dir_all(root).ok();
    }
}
