//! Provider bootstrap against the pinned alkanes-rs main commit.
//!
//! Mirrors what alkanes-cli's `SystemAlkanes::new_with_options` does for
//! our fixed shape (Qubitcoin RPC endpoint, project-local keystore),
//! without depending on `alkanes-cli-sys` (broken at the pinned rev) or
//! clap `Args`.

use crate::error::{LabcoatError, Result};
use crate::signer::{KeystoreSigner, PsbtFileSigner, RemoteSignerAdapter, Signer, SignerSpec};
use alkanes_cli_common::provider::ConcreteProvider;
use std::path::PathBuf;
use std::str::FromStr;
use std::sync::Arc;

/// A user-facing Labcoat deployment target.
///
/// `Labcoat` is the managed local network identity. It deliberately maps to
/// Bitcoin regtest only at protocol boundaries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NetworkTarget {
    Labcoat,
    Regtest,
    Signet,
    Testnet,
    Mainnet,
}

impl NetworkTarget {
    pub const ALLOWED: &'static str = "labcoat, regtest, signet, testnet, mainnet";

    pub fn id(self) -> &'static str {
        match self {
            Self::Labcoat => "labcoat",
            Self::Regtest => "regtest",
            Self::Signet => "signet",
            Self::Testnet => "testnet",
            Self::Mainnet => "mainnet",
        }
    }

    /// The Bitcoin network parameters used by the provider and wallet.
    pub fn bitcoin_network_id(self) -> &'static str {
        match self {
            Self::Labcoat | Self::Regtest => "regtest",
            Self::Signet => "signet",
            Self::Testnet => "testnet",
            Self::Mainnet => "mainnet",
        }
    }

    pub fn uses_regtest(self) -> bool {
        self.bitcoin_network_id() == "regtest"
    }
}

impl Default for NetworkTarget {
    fn default() -> Self {
        Self::Labcoat
    }
}

impl std::fmt::Display for NetworkTarget {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.id())
    }
}

impl FromStr for NetworkTarget {
    type Err = String;

    fn from_str(value: &str) -> std::result::Result<Self, Self::Err> {
        match value.trim().to_ascii_lowercase().as_str() {
            "labcoat" => Ok(Self::Labcoat),
            "regtest" => Ok(Self::Regtest),
            "signet" => Ok(Self::Signet),
            "testnet" => Ok(Self::Testnet),
            "mainnet" => Ok(Self::Mainnet),
            "oylnet" => {
                tracing::warn!("network 'oylnet' is deprecated; treating as 'regtest'");
                Ok(Self::Regtest)
            }
            other => Err(format!(
                "unknown network '{}'; use one of: {}",
                other,
                Self::ALLOWED
            )),
        }
    }
}

/// Connection + wallet settings for the toolkit.
#[derive(Debug, Clone)]
pub struct ToolkitConfig {
    /// Deployment target. Labcoat Network uses Bitcoin regtest underneath.
    pub network: NetworkTarget,
    /// Direct Qubitcoin RPC endpoint.
    pub rpc_url: String,
    /// Keystore path (project-local by default).
    pub wallet_file: PathBuf,
    /// Fee rate in sat/vB for state-changing operations.
    pub fee_rate: Option<f32>,
    /// Skip the per-transaction approval prompt on public networks
    /// (`--yes`). Regtest targets always auto-approve.
    pub assume_yes: bool,
    /// Durable-state environment (`.labcoat/state/<environment>/`).
    pub environment: String,
    /// Persistent Labcoat Network instance UUID (regenerated by
    /// `labcoat reset`), when the managed network is the target and the
    /// caller attached it. Used by durable state to detect a reset chain.
    pub labcoat_instance_id: Option<String>,
}

impl Default for ToolkitConfig {
    fn default() -> Self {
        Self {
            network: NetworkTarget::Labcoat,
            rpc_url: "http://127.0.0.1:18443".to_string(),
            wallet_file: PathBuf::from(".labcoat/wallet.json"),
            fee_rate: Some(2.0),
            assume_yes: false,
            environment: "default".to_string(),
            labcoat_instance_id: None,
        }
    }
}

impl ToolkitConfig {
    pub fn network_id(&self) -> &'static str {
        self.network.id()
    }

    pub fn bitcoin_network_id(&self) -> &'static str {
        self.network.bitcoin_network_id()
    }

    /// Refuse footgun setups. The keystore backend needs an explicit
    /// passphrase on every non-regtest network (mainnet, signet, AND
    /// testnet — real coins or not, a decryptable keystore deserves a real
    /// passphrase). External backends carry no local secret to unlock.
    pub fn require_signer_policy(&self, signer: &SignerSpec) -> Result<()> {
        match signer {
            SignerSpec::Keystore { passphrase: None } if !self.network.uses_regtest() => {
                Err(LabcoatError::new(
                    "WALLET_LOCKED",
                    format!("a wallet passphrase is required on {}", self.network_id()),
                    "set LABCOAT_WALLET_PASSPHRASE",
                ))
            }
            _ => Ok(()),
        }
    }

    /// Back-compat shim for callers that still think in passphrases.
    pub fn require_passphrase_policy(&self, passphrase: &Option<String>) -> Result<()> {
        self.require_signer_policy(&SignerSpec::Keystore {
            passphrase: passphrase.clone(),
        })
    }
}

/// Build a ready `ConcreteProvider`. When `wallet_needed` is true the
/// keystore at `wallet_file` is loaded (and unlocked if a passphrase is
/// given); read-only commands skip that.
pub async fn connect(
    config: &ToolkitConfig,
    passphrase: Option<String>,
    wallet_needed: bool,
) -> Result<ConcreteProvider> {
    let network = config.bitcoin_network_id();

    // Network params + process-global network (address derivation/signing).
    let params =
        alkanes_cli_common::network::NetworkParams::from_network_str(network).map_err(|e| {
            LabcoatError::new(
                "CONFIG_INVALID",
                format!("unknown Bitcoin network '{network}': {e}"),
                "use one of: labcoat, regtest, signet, testnet, mainnet",
            )
        })?;
    alkanes_cli_common::network::set_network(params);

    // The keystore writer assumes its parent directory exists.
    if let Some(parent) = config.wallet_file.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent).map_err(|e| {
                LabcoatError::new(
                    "TOOLKIT_ERROR",
                    format!("cannot create {}: {}", parent.display(), e),
                    "check permissions on the project directory",
                )
            })?;
        }
    }

    let mut provider = ConcreteProvider::new_with_headers(
        Some(config.rpc_url.clone()),
        config.rpc_url.clone(),
        None,
        None,
        None,
        None,
        network.to_string(),
        Some(config.wallet_file.clone()),
        Vec::new(),
    )
    .await
    .map_err(|e| LabcoatError::classify(e.into()))?;
    provider.rpc_config.qubitcoin_rpc_url = Some(config.rpc_url.clone());
    // Upstream's legacy URL selector does not consider qubitcoin_rpc_url for
    // Esplora/Ord commands. Point its JSON-RPC fallback at the same direct
    // Qubitcoin endpoint so `call()` can apply the secondaryview translation.
    provider.rpc_config.jsonrpc_url = Some(config.rpc_url.clone());

    // In-memory cache: deterministic, no ~/.alkanes/cache.sqlite3 side state.
    provider = provider.with_cache(std::sync::Arc::new(
        alkanes_cli_common::cache::in_memory::InMemoryCache::new(),
    ));

    provider.set_passphrase(passphrase);

    if wallet_needed {
        check_keystore_hygiene(&config.wallet_file)?;
        ConcreteProvider::initialize(&mut provider)
            .await
            .map_err(|e| LabcoatError::classify(e.into()))?;
    }

    Ok(provider)
}

/// The KDF strength labcoat-created keystores use; files claiming less are
/// rejected before decryption (the file records its own iteration count, so
/// a tampered keystore could otherwise downgrade the KDF to nothing).
const KEYSTORE_PBKDF2_FLOOR: u64 = 131_072;

fn check_keystore_hygiene(path: &PathBuf) -> Result<()> {
    let Ok(raw) = std::fs::read(path) else {
        // Missing file surfaces as WALLET_MISSING from initialize().
        return Ok(());
    };

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(metadata) = std::fs::metadata(path) {
            if metadata.permissions().mode() & 0o077 != 0 {
                tracing::warn!(
                    "{} is readable by other users; run `chmod 600 {}`",
                    path.display(),
                    path.display()
                );
            }
        }
    }

    let Ok(parsed) = serde_json::from_slice::<serde_json::Value>(&raw) else {
        return Ok(()); // initialize() reports unparseable keystores itself
    };
    if let Some(iterations) = parsed
        .get("pbkdf2_params")
        .and_then(|params| params.get("iterations"))
        .and_then(|value| value.as_u64())
    {
        if iterations < KEYSTORE_PBKDF2_FLOOR {
            return Err(LabcoatError::new(
                "KEYSTORE_WEAK",
                format!(
                    "{} declares only {iterations} PBKDF2 iterations (labcoat requires at least {KEYSTORE_PBKDF2_FLOOR}); the file may have been tampered with",
                    path.display()
                ),
                "restore the keystore from a trusted backup, or re-create it with `labcoat wallet init`",
            ));
        }
    }
    Ok(())
}

/// A provider plus the signer that authorizes its transactions.
pub struct Connected {
    pub provider: ConcreteProvider,
    pub signer: Arc<dyn Signer>,
}

/// Build a provider ready to sign through the configured backend.
///
/// - `Keystore`: unlock with the passphrase; the provider's own signing path
///   stays active (identical to historical behavior) and the returned
///   [`KeystoreSigner`] serves flows that sign PSBTs directly.
/// - `PsbtFile`: install a [`RemoteSignerAdapter`] so every signature the
///   upstream executor requests round-trips through the PSBT directory. The
///   keystore is unlocked only when a passphrase is available — upstream's
///   `get_internal_key` (PSBT metadata, not signing) still derives from the
///   mnemonic at the pinned rev; signatures never come from the local
///   keystore on this path.
pub async fn connect_signing(config: &ToolkitConfig, spec: &SignerSpec) -> Result<Connected> {
    config.require_signer_policy(spec)?;
    match spec {
        SignerSpec::Keystore { passphrase } => {
            let provider = connect(config, passphrase.clone(), true).await?;
            let signer: Arc<dyn Signer> = Arc::new(KeystoreSigner::from_provider(&provider)?);
            Ok(Connected { provider, signer })
        }
        SignerSpec::PsbtFile { dir, passphrase } => {
            let provider = connect(config, passphrase.clone(), true).await?;
            let signer: Arc<dyn Signer> =
                Arc::new(PsbtFileSigner::from_provider(&provider, dir.clone())?);
            let provider =
                provider.with_remote_signer(Some(Arc::new(RemoteSignerAdapter(signer.clone()))));
            Ok(Connected { provider, signer })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alkanes_cli_common::commands::{Commands, EsploraCommands};
    use alkanes_cli_common::rpc::{determine_rpc_call_type, get_rpc_url, RpcCallType};

    #[tokio::test]
    async fn provider_routes_legacy_esplora_commands_to_qubitcoin() {
        let config = ToolkitConfig::default();
        let provider = connect(&config, None, false).await.unwrap();
        let tip_height = Commands::Esplora {
            command: EsploraCommands::BlocksTipHeight { raw: false },
        };

        assert_eq!(
            provider.rpc_config.qubitcoin_rpc_url.as_deref(),
            Some("http://127.0.0.1:18443")
        );
        assert_eq!(
            provider.rpc_config.jsonrpc_url.as_deref(),
            provider.rpc_config.qubitcoin_rpc_url.as_deref()
        );
        assert!(provider.rpc_config.esplora_url.is_none());
        assert!(provider.rpc_config.is_qubitcoin_mode());
        assert_eq!(
            get_rpc_url(&provider.rpc_config, &tip_height).unwrap(),
            "http://127.0.0.1:18443"
        );
        assert_eq!(
            determine_rpc_call_type(&provider.rpc_config, &tip_height),
            RpcCallType::JsonRpc
        );
    }

    #[test]
    fn toolkit_defaults_to_local_qubitcoin_rpc() {
        assert_eq!(ToolkitConfig::default().rpc_url, "http://127.0.0.1:18443");
    }

    #[test]
    fn labcoat_target_maps_to_regtest_only_at_protocol_boundaries() {
        let config = ToolkitConfig::default();
        assert_eq!(config.network_id(), "labcoat");
        assert_eq!(config.bitcoin_network_id(), "regtest");
        assert!(config.network.uses_regtest());
    }

    #[test]
    fn parses_supported_targets_and_deprecated_oylnet() {
        assert_eq!(
            NetworkTarget::from_str("labcoat").unwrap(),
            NetworkTarget::Labcoat
        );
        assert_eq!(
            NetworkTarget::from_str("regtest").unwrap(),
            NetworkTarget::Regtest
        );
        assert_eq!(
            NetworkTarget::from_str("oylnet").unwrap(),
            NetworkTarget::Regtest
        );
        assert!(NetworkTarget::from_str("unknown").is_err());
    }

    #[test]
    fn passphrase_policy_distinguishes_local_and_public_targets() {
        let mut config = ToolkitConfig::default();
        assert!(config.require_passphrase_policy(&None).is_ok());

        config.network = NetworkTarget::Regtest;
        assert!(config.require_passphrase_policy(&None).is_ok());

        config.network = NetworkTarget::Signet;
        assert!(config.require_passphrase_policy(&None).is_err());
        assert!(config
            .require_passphrase_policy(&Some("secret".to_string()))
            .is_ok());

        // Testnet used to slip through the gate; it is a public network too.
        config.network = NetworkTarget::Testnet;
        assert!(config.require_passphrase_policy(&None).is_err());

        config.network = NetworkTarget::Mainnet;
        assert!(config.require_passphrase_policy(&None).is_err());
    }

    #[test]
    fn external_signers_need_no_passphrase_on_public_networks() {
        let config = ToolkitConfig {
            network: NetworkTarget::Mainnet,
            ..ToolkitConfig::default()
        };
        assert!(config
            .require_signer_policy(&SignerSpec::PsbtFile {
                dir: PathBuf::from("psbts"),
                passphrase: None,
            })
            .is_ok());
    }
}
