// Generated by `labcoat generate web` — do not edit.

/** One typed parameter of an ABI method. */
export interface AbiParam {
  name: string
  /** ABI type name, e.g. "u128", "AlkaneId", "String". */
  type: string
}

/** One contract method: dispatch opcode plus its typed signature. */
export interface AbiMethod {
  name: string
  /** Dispatch opcode (a u128). */
  opcode: bigint
  params: AbiParam[]
  /** ABI return type name, e.g. "u128", "String", "Vec<u8>", "void". */
  returns: string
}

/** A contract ABI as extracted from its canonical `__meta` export. */
export interface AbiDocument {
  contract: string
  methods: AbiMethod[]
}
