// Generated by `labcoat generate web` — do not edit.

import type { AbiDocument } from "./document"
import { abiOverwriteSeries } from "./overwrite-series"
import { abiOverwriteTestToken } from "./overwrite-test-token"

export type { AbiDocument, AbiMethod, AbiParam } from "./document"

/** Every built contract ABI, keyed by build artifact name. */
export const ABIS: Record<string, AbiDocument> = {
  "overwrite-series": abiOverwriteSeries,
  "overwrite-test-token": abiOverwriteTestToken,
}
