// Generated by `labcoat generate web` — do not edit.

import type { AbiDocument } from "./document"

/** ABI of the overwrite-series build artifact. */
export const abiOverwriteSeries: AbiDocument = {
  contract: "OverwriteSeries",
  methods: [
    {
      name: "initialize",
      opcode: 0n,
      params: [
        { name: "underlying", type: "AlkaneId" },
        { name: "strike", type: "AlkaneId" },
        { name: "writer_claim", type: "AlkaneId" },
        { name: "underlying_per_call", type: "u128" },
        { name: "strike_per_call", type: "u128" },
        { name: "expiry_height", type: "u128" },
        { name: "quantity", type: "u128" },
      ],
      returns: "void",
    },
    {
      name: "fund",
      opcode: 1n,
      params: [],
      returns: "void",
    },
    {
      name: "exercise",
      opcode: 10n,
      params: [],
      returns: "void",
    },
    {
      name: "redeem",
      opcode: 20n,
      params: [],
      returns: "void",
    },
    {
      name: "get_name",
      opcode: 99n,
      params: [],
      returns: "String",
    },
    {
      name: "get_symbol",
      opcode: 100n,
      params: [],
      returns: "String",
    },
    {
      name: "get_total_supply",
      opcode: 101n,
      params: [],
      returns: "u128",
    },
    {
      name: "get_series",
      opcode: 110n,
      params: [],
      returns: "Vec<u8>",
    },
  ],
}
