// Generated by `labcoat generate web` — do not edit.

import type { AbiDocument } from "./document"

/** ABI of the overwrite-test-token build artifact. */
export const abiOverwriteTestToken: AbiDocument = {
  contract: "TestToken",
  methods: [
    {
      name: "initialize",
      opcode: 0n,
      params: [
        { name: "kind", type: "u128" },
        { name: "supply", type: "u128" },
      ],
      returns: "void",
    },
    {
      name: "forward",
      opcode: 1n,
      params: [],
      returns: "void",
    },
    {
      name: "get_name",
      opcode: 99n,
      params: [],
      returns: "String",
    },
    {
      name: "get_symbol",
      opcode: 100n,
      params: [],
      returns: "String",
    },
    {
      name: "get_total_supply",
      opcode: 101n,
      params: [],
      returns: "u128",
    },
  ],
}
