// Generated by `labcoat generate web` — do not edit.
//
// Read-only browser client for the Labcoat unified JSON-RPC endpoint
// (Qubitcoin node + Alkanes secondary view). No signing, no key material,
// no state mutation. Self-contained: no runtime dependencies.

import { MANIFEST } from "./manifest"
import { ABIS } from "./abi"
import type { AbiMethod } from "./abi"

const U128_MAX = (1n << 128n) - 1n
const ALKANES_PROTOCOL_TAG = 1n

/* ---------------------------------- hex ---------------------------------- */

function bytesToHex(bytes: Uint8Array): string {
  let out = ""
  for (const byte of bytes) out += byte.toString(16).padStart(2, "0")
  return out
}

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex
  if (clean.length % 2 !== 0 || /[^0-9a-fA-F]/.test(clean)) {
    throw new LabcoatClientError("RESPONSE_INVALID", `invalid hex payload: ${hex.slice(0, 32)}…`)
  }
  const bytes = new Uint8Array(clean.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

/* --------------------------- LEB128 / protobuf ---------------------------- */

function pushVarint(out: number[], value: bigint): void {
  if (value < 0n) throw new LabcoatClientError("ARG_INVALID", "varint values must be non-negative")
  let v = value
  for (;;) {
    const byte = Number(v & 0x7fn)
    v >>= 7n
    if (v === 0n) {
      out.push(byte)
      return
    }
    out.push(byte | 0x80)
  }
}

/** LEB128 varint list — the cellpack encoding: [block, tx, opcode, ...args]. */
function encodeCellpack(values: bigint[]): Uint8Array {
  const out: number[] = []
  for (const value of values) pushVarint(out, value)
  return Uint8Array.from(out)
}

function pushProtoVarintField(out: number[], field: number, value: bigint): void {
  pushVarint(out, BigInt(field * 8))
  pushVarint(out, value)
}

function pushProtoBytesField(out: number[], field: number, value: Uint8Array): void {
  pushVarint(out, BigInt(field * 8 + 2))
  pushVarint(out, BigInt(value.length))
  for (const byte of value) out.push(byte)
}

/** Minimal protobuf wire reader (varint + length-delimited + fixed skips). */
class ProtoReader {
  private offset = 0

  constructor(private readonly bytes: Uint8Array) {}

  atEnd(): boolean {
    return this.offset >= this.bytes.length
  }

  readVarint(): bigint {
    let value = 0n
    let shift = 0n
    for (;;) {
      if (this.offset >= this.bytes.length) {
        throw new LabcoatClientError("RESPONSE_INVALID", "truncated protobuf varint")
      }
      const byte = this.bytes[this.offset++]
      value |= BigInt(byte & 0x7f) << shift
      if ((byte & 0x80) === 0) return value
      shift += 7n
      if (shift > 133n) {
        throw new LabcoatClientError("RESPONSE_INVALID", "oversized protobuf varint")
      }
    }
  }

  readField(): { field: number; wire: number } {
    const tag = this.readVarint()
    return { field: Number(tag >> 3n), wire: Number(tag & 7n) }
  }

  readBytes(): Uint8Array {
    const length = Number(this.readVarint())
    if (this.offset + length > this.bytes.length) {
      throw new LabcoatClientError("RESPONSE_INVALID", "truncated protobuf payload")
    }
    const slice = this.bytes.subarray(this.offset, this.offset + length)
    this.offset += length
    return slice
  }

  skip(wire: number): void {
    if (wire === 0) {
      this.readVarint()
    } else if (wire === 1) {
      this.offset += 8
    } else if (wire === 2) {
      this.readBytes()
    } else if (wire === 5) {
      this.offset += 4
    } else {
      throw new LabcoatClientError("RESPONSE_INVALID", `unsupported protobuf wire type ${wire}`)
    }
    if (this.offset > this.bytes.length) {
      throw new LabcoatClientError("RESPONSE_INVALID", "truncated protobuf payload")
    }
  }
}

/** protorune/alkanes uint128 message: { lo: u64 = 1, hi: u64 = 2 }. */
function decodeUint128(bytes: Uint8Array): bigint {
  const reader = new ProtoReader(bytes)
  let lo = 0n
  let hi = 0n
  while (!reader.atEnd()) {
    const { field, wire } = reader.readField()
    if (field === 1 && wire === 0) lo = reader.readVarint()
    else if (field === 2 && wire === 0) hi = reader.readVarint()
    else reader.skip(wire)
  }
  return (hi << 64n) | lo
}

/* --------------------------------- errors --------------------------------- */

export type LabcoatClientErrorCode =
  | "RPC_UNREACHABLE"
  | "RPC_ERROR"
  | "RESPONSE_INVALID"
  | "CONTRACT_UNKNOWN"
  | "METHOD_UNKNOWN"
  | "ARG_INVALID"

export class LabcoatClientError extends Error {
  constructor(
    public readonly code: LabcoatClientErrorCode,
    message: string,
  ) {
    super(message)
    this.name = "LabcoatClientError"
  }
}

/* --------------------------------- results -------------------------------- */

export interface AlkaneRef {
  /** Canonical decimal digits. */
  block: string
  tx: string
}

export interface AlkaneBalance {
  id: AlkaneRef
  /** "block:tx" convenience key. */
  key: string
  name: string
  symbol: string
  /** Total base units across every outpoint the address controls. */
  balance: bigint
}

export type SimulateValue = bigint | string | Uint8Array | AlkaneRef | null

export interface SimulateResult {
  status: "success" | "revert"
  gasUsed: bigint
  /** Revert reason, when the contract reverted. */
  error: string | null
  /** Raw return bytes. */
  data: Uint8Array
  /**
   * `data` decoded per the ABI return type: u128 → bigint, String → string,
   * AlkaneId → { block, tx } decimal strings, Vec<u8> → Uint8Array. Null on
   * revert, `void` returns, numeric-opcode calls, and unknown types.
   */
  value: SimulateValue
}

/** One argument per ABI parameter: bigint/number, decimal or 0x-hex string,
 * "block:tx" for AlkaneId parameters, or arbitrary text for String ones. */
export type SimulateArg = bigint | number | string

/* ------------------------------ arg encoding ------------------------------ */

function parseU128(value: SimulateArg, label: string): bigint {
  let parsed: bigint
  if (typeof value === "bigint") {
    parsed = value
  } else if (typeof value === "number") {
    if (!Number.isSafeInteger(value) || value < 0) {
      throw new LabcoatClientError("ARG_INVALID", `${label} must be a non-negative safe integer`)
    }
    parsed = BigInt(value)
  } else if (/^0x[0-9a-fA-F]+$/.test(value)) {
    parsed = BigInt(value)
  } else if (/^(0|[1-9][0-9]*)$/.test(value)) {
    parsed = BigInt(value)
  } else {
    throw new LabcoatClientError("ARG_INVALID", `${label} must be a canonical decimal or 0x-hex u128`)
  }
  if (parsed < 0n || parsed > U128_MAX) {
    throw new LabcoatClientError("ARG_INVALID", `${label} does not fit in a u128`)
  }
  return parsed
}

function parseAlkaneRef(value: SimulateArg, label: string): { block: bigint; tx: bigint } {
  if (typeof value !== "string" || !value.includes(":")) {
    throw new LabcoatClientError("ARG_INVALID", `${label} must use decimal "block:tx" syntax`)
  }
  const [block, tx, ...rest] = value.split(":")
  if (rest.length > 0) {
    throw new LabcoatClientError("ARG_INVALID", `${label} must use decimal "block:tx" syntax`)
  }
  return {
    block: parseU128(block, `${label} block`),
    tx: parseU128(tx, `${label} tx`),
  }
}

/** NUL-terminated UTF-8 packed into little-endian u128 cellpack words. */
function encodeStringArg(value: SimulateArg, label: string): bigint[] {
  if (typeof value !== "string") {
    throw new LabcoatClientError("ARG_INVALID", `${label} must be a string`)
  }
  const bytes = new TextEncoder().encode(value)
  if (bytes.includes(0)) {
    throw new LabcoatClientError("ARG_INVALID", `${label} cannot contain a null byte`)
  }
  const terminated = new Uint8Array(bytes.length + 1)
  terminated.set(bytes)
  const words: bigint[] = []
  for (let i = 0; i < terminated.length; i += 16) {
    const chunk = terminated.subarray(i, i + 16)
    let word = 0n
    for (let j = 0; j < chunk.length; j++) {
      word |= BigInt(chunk[j]) << BigInt(8 * j)
    }
    words.push(word)
  }
  return words
}

function encodeAbiArgs(method: AbiMethod, args: SimulateArg[]): bigint[] {
  if (args.length !== method.params.length) {
    const expected = method.params.map((p) => `${p.name}: ${p.type}`).join(", ")
    throw new LabcoatClientError(
      "ARG_INVALID",
      `method ${method.name} expects ${method.params.length} parameter(s) (${expected}), received ${args.length}`,
    )
  }
  const words: bigint[] = []
  for (let i = 0; i < method.params.length; i++) {
    const param = method.params[i]
    const label = `parameter ${param.name}`
    if (param.type === "u128") {
      words.push(parseU128(args[i], label))
    } else if (param.type === "AlkaneId") {
      const ref = parseAlkaneRef(args[i], label)
      words.push(ref.block, ref.tx)
    } else if (param.type === "String") {
      words.push(...encodeStringArg(args[i], label))
    } else {
      throw new LabcoatClientError(
        "ARG_INVALID",
        `ABI type ${param.type} is not supported by the generated client`,
      )
    }
  }
  return words
}

/* ----------------------------- return decoding ---------------------------- */

function decodeLeU128(bytes: Uint8Array): bigint {
  let value = 0n
  for (let i = 0; i < bytes.length; i++) {
    value |= BigInt(bytes[i]) << BigInt(8 * i)
  }
  return value
}

function decodeReturn(returns: string, data: Uint8Array): SimulateValue {
  if (returns === "u128") {
    if (data.length > 16) return null
    return decodeLeU128(data)
  }
  if (returns === "String") {
    return new TextDecoder("utf-8", { fatal: false }).decode(data)
  }
  if (returns === "Vec<u8>") {
    return data
  }
  if (returns === "AlkaneId") {
    if (data.length !== 32) return null
    return {
      block: decodeLeU128(data.subarray(0, 16)).toString(),
      tx: decodeLeU128(data.subarray(16, 32)).toString(),
    }
  }
  return null
}

/* ------------------------------- the client ------------------------------- */

export interface LabcoatWebClientOptions {
  /**
   * JSON-RPC endpoint the browser can actually reach — typically a
   * same-origin path (e.g. "/rpc") proxied to the manifest's rpcUrl by the
   * app's dev server. Defaults to the manifest's rpcUrl.
   */
  baseUrl?: string
  /** Fetch implementation (for tests and non-browser runtimes). */
  fetchFn?: typeof fetch
}

export class LabcoatWebClient {
  readonly baseUrl: string
  private readonly fetchFn: typeof fetch
  private requestId = 0

  constructor(options: LabcoatWebClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? MANIFEST.rpcUrl
    const fetchFn = options.fetchFn ?? globalThis.fetch
    if (typeof fetchFn !== "function") {
      throw new LabcoatClientError("RPC_UNREACHABLE", "no fetch implementation available")
    }
    this.fetchFn = fetchFn.bind(globalThis)
  }

  private async rpc(method: string, params: unknown[]): Promise<unknown> {
    let response: Response
    try {
      response = await this.fetchFn(this.baseUrl, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ jsonrpc: "2.0", id: ++this.requestId, method, params }),
      })
    } catch (cause) {
      throw new LabcoatClientError(
        "RPC_UNREACHABLE",
        `cannot reach ${this.baseUrl}: ${cause instanceof Error ? cause.message : String(cause)}`,
      )
    }
    if (!response.ok) {
      throw new LabcoatClientError("RPC_ERROR", `${method} failed: HTTP ${response.status}`)
    }
    let envelope: { result?: unknown; error?: { message?: string; code?: number } | null }
    try {
      envelope = (await response.json()) as typeof envelope
    } catch {
      throw new LabcoatClientError("RESPONSE_INVALID", `${method} returned a non-JSON body`)
    }
    if (envelope.error != null) {
      throw new LabcoatClientError(
        "RPC_ERROR",
        `${method} failed: ${envelope.error.message ?? JSON.stringify(envelope.error)}`,
      )
    }
    return envelope.result
  }

  /** A metashrew view over the Alkanes secondary index; protobuf in and out. */
  private async view(view: string, request: Uint8Array): Promise<Uint8Array> {
    const result = await this.rpc("secondaryview", [
      "alkanes",
      view,
      `0x${bytesToHex(request)}`,
    ])
    if (typeof result !== "string") {
      throw new LabcoatClientError("RESPONSE_INVALID", `${view} returned a non-string result`)
    }
    return hexToBytes(result)
  }

  /** Height of the Alkanes secondary index — the state every read reflects. */
  async getIndexedHeight(): Promise<number> {
    const result = await this.rpc("secondaryheight", ["alkanes"])
    const height =
      typeof result === "number"
        ? result
        : typeof result === "string"
          ? Number.parseInt(result, 10)
          : Number.NaN
    if (!Number.isSafeInteger(height) || height < 0) {
      throw new LabcoatClientError("RESPONSE_INVALID", `invalid indexed height: ${String(result)}`)
    }
    return height
  }

  /**
   * Alkanes balances held by `address`, summed across its outpoints and
   * sorted by Alkane id. Amounts are full u128 base units.
   */
  async getAlkanesBalances(address: string): Promise<AlkaneBalance[]> {
    if (address.length === 0) {
      throw new LabcoatClientError("ARG_INVALID", "address must not be empty")
    }
    // protorune.ProtorunesWalletRequest { wallet = 1, protocol_tag = 2 }
    const request: number[] = []
    pushProtoBytesField(request, 1, new TextEncoder().encode(address))
    const protocolTag: number[] = []
    pushProtoVarintField(protocolTag, 1, ALKANES_PROTOCOL_TAG)
    pushProtoBytesField(request, 2, Uint8Array.from(protocolTag))

    const response = await this.view("protorunesbyaddress", Uint8Array.from(request))
    const totals = new Map<string, { block: bigint; tx: bigint; name: string; symbol: string; balance: bigint }>()

    // protorune.WalletResponse { outpoints: OutpointResponse[] = 1 }
    const wallet = new ProtoReader(response)
    while (!wallet.atEnd()) {
      const { field, wire } = wallet.readField()
      if (field !== 1 || wire !== 2) {
        wallet.skip(wire)
        continue
      }
      // OutpointResponse { balances: BalanceSheet = 1 }
      const outpoint = new ProtoReader(wallet.readBytes())
      while (!outpoint.atEnd()) {
        const item = outpoint.readField()
        if (item.field !== 1 || item.wire !== 2) {
          outpoint.skip(item.wire)
          continue
        }
        // BalanceSheet { entries: BalanceSheetItem[] = 1 }
        const sheet = new ProtoReader(outpoint.readBytes())
        while (!sheet.atEnd()) {
          const entry = sheet.readField()
          if (entry.field !== 1 || entry.wire !== 2) {
            sheet.skip(entry.wire)
            continue
          }
          decodeBalanceSheetItem(sheet.readBytes(), totals)
        }
      }
    }

    const balances = [...totals.values()].map((entry) => ({
      id: { block: entry.block.toString(), tx: entry.tx.toString() },
      key: `${entry.block}:${entry.tx}`,
      name: entry.name,
      symbol: entry.symbol,
      balance: entry.balance,
    }))
    balances.sort((left, right) => {
      const leftBlock = BigInt(left.id.block)
      const rightBlock = BigInt(right.id.block)
      if (leftBlock !== rightBlock) return leftBlock < rightBlock ? -1 : 1
      const leftTx = BigInt(left.id.tx)
      const rightTx = BigInt(right.id.tx)
      if (leftTx === rightTx) return 0
      return leftTx < rightTx ? -1 : 1
    })
    return balances
  }

  /**
   * Read-only simulation against indexed chain state. `contract` is a
   * manifest contract name or a "block:tx" id; `method` is an ABI method
   * name (typed args, decoded return) or a decimal opcode (raw u128 args,
   * raw return). Pass `options.height` to reuse an already-fetched indexed
   * height and save a round trip.
   */
  async simulate(
    contract: string,
    method: string,
    args: SimulateArg[] = [],
    options: { height?: number } = {},
  ): Promise<SimulateResult> {
    const target = this.resolveContract(contract)
    let opcode: bigint
    let words: bigint[]
    let returns: string | null
    if (/^(0|[1-9][0-9]*)$/.test(method)) {
      opcode = parseU128(method, "opcode")
      words = args.map((arg, index) => parseU128(arg, `argument ${index}`))
      returns = null
    } else {
      const abiMethod = this.resolveMethod(target, method)
      opcode = abiMethod.opcode
      words = encodeAbiArgs(abiMethod, args)
      returns = abiMethod.returns
    }

    const height = options.height ?? (await this.getIndexedHeight())
    const calldata = encodeCellpack([target.block, target.tx, opcode, ...words])
    // alkanes.MessageContextParcel { height = 4, calldata = 5 }
    const parcel: number[] = []
    pushProtoVarintField(parcel, 4, BigInt(height))
    pushProtoBytesField(parcel, 5, calldata)

    const response = await this.view("simulate", Uint8Array.from(parcel))

    // alkanes.SimulateResponse { execution = 1, gas_used = 2, error = 3 }
    let data: Uint8Array = new Uint8Array(0)
    let gasUsed = 0n
    let error: string | null = null
    const reader = new ProtoReader(response)
    while (!reader.atEnd()) {
      const { field, wire } = reader.readField()
      if (field === 1 && wire === 2) {
        // alkanes.ExtendedCallResponse { data = 3 }
        const execution = new ProtoReader(reader.readBytes())
        while (!execution.atEnd()) {
          const item = execution.readField()
          if (item.field === 3 && item.wire === 2) data = execution.readBytes()
          else execution.skip(item.wire)
        }
      } else if (field === 2 && wire === 0) {
        gasUsed = reader.readVarint()
      } else if (field === 3 && wire === 2) {
        error = new TextDecoder("utf-8", { fatal: false }).decode(reader.readBytes())
        if (error.length === 0) error = null
      } else {
        reader.skip(wire)
      }
    }

    const status = error === null ? "success" : "revert"
    return {
      status,
      gasUsed,
      error,
      data,
      value: status === "success" && returns !== null ? decodeReturn(returns, data) : null,
    }
  }

  private resolveContract(contract: string): { block: bigint; tx: bigint; artifact: string | null } {
    if (contract.includes(":")) {
      const ref = parseAlkaneRef(contract, "contract id")
      return { block: ref.block, tx: ref.tx, artifact: null }
    }
    const deployment = MANIFEST.contracts[contract]
    if (deployment === undefined) {
      const known = Object.keys(MANIFEST.contracts).join(", ")
      throw new LabcoatClientError(
        "CONTRACT_UNKNOWN",
        `no contract "${contract}" in the generated manifest${known.length > 0 ? ` (known: ${known})` : ""}`,
      )
    }
    const ref = parseAlkaneRef(deployment.id, `manifest id for ${contract}`)
    return { block: ref.block, tx: ref.tx, artifact: deployment.artifact }
  }

  private resolveMethod(
    target: { artifact: string | null },
    method: string,
  ): AbiMethod {
    if (target.artifact === null) {
      throw new LabcoatClientError(
        "METHOD_UNKNOWN",
        `method "${method}" needs ABI metadata; call by manifest contract name or use a numeric opcode`,
      )
    }
    const abi = ABIS[target.artifact]
    const resolved = abi?.methods.find((candidate) => candidate.name === method)
    if (resolved === undefined) {
      const available = abi?.methods.map((candidate) => candidate.name).join(", ") ?? ""
      throw new LabcoatClientError(
        "METHOD_UNKNOWN",
        `ABI method "${method}" was not found${available.length > 0 ? `; available methods: ${available}` : ""}`,
      )
    }
    return resolved
  }
}

function decodeBalanceSheetItem(
  bytes: Uint8Array,
  totals: Map<string, { block: bigint; tx: bigint; name: string; symbol: string; balance: bigint }>,
): void {
  // protorune.BalanceSheetItem { rune: Rune = 1, balance: uint128 = 2 }
  let block: bigint | null = null
  let tx: bigint | null = null
  let name = ""
  let symbol = ""
  let balance = 0n
  const reader = new ProtoReader(bytes)
  while (!reader.atEnd()) {
    const { field, wire } = reader.readField()
    if (field === 1 && wire === 2) {
      // protorune.Rune { runeId = 1, name = 2, symbol = 5 }
      const rune = new ProtoReader(reader.readBytes())
      while (!rune.atEnd()) {
        const item = rune.readField()
        if (item.field === 1 && item.wire === 2) {
          // protorune.ProtoruneRuneId { height: uint128 = 1, txindex: uint128 = 2 }
          const runeId = new ProtoReader(rune.readBytes())
          while (!runeId.atEnd()) {
            const part = runeId.readField()
            if (part.field === 1 && part.wire === 2) block = decodeUint128(runeId.readBytes())
            else if (part.field === 2 && part.wire === 2) tx = decodeUint128(runeId.readBytes())
            else runeId.skip(part.wire)
          }
        } else if (item.field === 2 && item.wire === 2) {
          name = new TextDecoder("utf-8", { fatal: false }).decode(rune.readBytes())
        } else if (item.field === 5 && item.wire === 2) {
          symbol = new TextDecoder("utf-8", { fatal: false }).decode(rune.readBytes())
        } else {
          rune.skip(item.wire)
        }
      }
    } else if (field === 2 && wire === 2) {
      balance = decodeUint128(reader.readBytes())
    } else {
      reader.skip(wire)
    }
  }
  if (block === null || tx === null) return
  const key = `${block}:${tx}`
  const existing = totals.get(key)
  if (existing === undefined) {
    totals.set(key, { block, tx, name, symbol, balance })
  } else {
    existing.balance += balance
    if (existing.name.length === 0) existing.name = name
    if (existing.symbol.length === 0) existing.symbol = symbol
  }
}
