// Generated by `labcoat generate web` — do not edit.
//
// Derived from labcoat.lock (network "labcoat") and built ABI
// artifacts. Regenerate after every deploy or ABI change.

/** One labcoat.lock deployment record, projected for browser reads. */
export interface ContractDeployment {
  /** Alkanes id as canonical decimal "block:tx". */
  id: string
  /** Deploy transaction id. */
  txid: string
  /** sha256 of the deployed wasm, when recorded. */
  wasmSha256: string | null
  /** Chain instance id (the hash of block 1) the record was written against. */
  chainId: string | null
  /** Local build artifact whose ABI describes this deployment, when known. */
  artifact: string | null
}

export interface WebManifest {
  /** Labcoat network target these artifacts were generated for. */
  network: string
  /** Bitcoin network parameters underneath the target. */
  bitcoinNetwork: string
  /**
   * The unified JSON-RPC endpoint (node + Alkanes secondary view) at
   * generation time. Browsers normally reach it through a same-origin dev
   * proxy or rewrite instead of calling it directly.
   */
  rpcUrl: string
  /**
   * Chain instance id shared by every deployment record, or null when
   * records are missing one or disagree. Compare against live chain state
   * to detect a reset network with stale records.
   */
  chainId: string | null
  /** Deployment records keyed by labcoat.lock contract name. */
  contracts: Record<string, ContractDeployment>
}

export const MANIFEST: WebManifest = {
  network: "labcoat",
  bitcoinNetwork: "regtest",
  rpcUrl: "http://127.0.0.1:18443",
  chainId: null,
  contracts: {
    "fire": {
      id: "4:65011",
      txid: "1111111111111111111111111111111111111111111111111111111111111111",
      wasmSha256: "73767b02082691113f2035e0f5f88c50985c28ee9eab23f6ae58fd3821aff265",
      chainId: "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
      artifact: "overwrite-test-token",
    },
    "legacy": {
      id: "4:100",
      txid: "4444444444444444444444444444444444444444444444444444444444444444",
      wasmSha256: null,
      chainId: null,
      artifact: null,
    },
    "series": {
      id: "4:65014",
      txid: "2222222222222222222222222222222222222222222222222222222222222222",
      wasmSha256: "8f3c2c41d651a8a03e517b93df0ded4ffe17a9d579cabf3503c2a9578965f02d",
      chainId: "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
      artifact: "overwrite-series",
    },
    "usd": {
      id: "4:65012",
      txid: "3333333333333333333333333333333333333333333333333333333333333333",
      wasmSha256: "73767b02082691113f2035e0f5f88c50985c28ee9eab23f6ae58fd3821aff265",
      chainId: "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
      artifact: "overwrite-test-token",
    },
  },
}
